### 1 ###
[[redirects]]
  from = "/1"
  to = "https://pseudo-flix.pro/media/tmdb-movie-776503-coda"
  status = 301
  force = true

[[redirects]]
  from = "/1.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYzkyNzNiMDItMGU1Yy00NmEyLWE4N2ItMjkzMDZmMmVhNDU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/1.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/1"
  status = 301
  force = true

### 2 ###
[[redirects]]
  from = "/2"
  to = "https://www.youtube.com/watch?v=2ErfXLkVBMY"
  status = 301
  force = true

[[redirects]]
  from = "/2.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTY4YjY3ZDgtYjVhZS00MWY4LTlkYmMtNGI4ZGY4YzhiZmIwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/2.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/2"
  status = 301
  force = true

### 3 ###
[[redirects]]
  from = "/3"
  to = "https://pseudo-flix.pro/media/tmdb-movie-15859-a-moment-to-remember"
  status = 301
  force = true

[[redirects]]
  from = "/3.poster"
  to = "https://m.media-amazon.com/images/M/MV5BODYzODg5Mjg3Ml5BMl5BanBnXkFtZTgwNDM1MDQ2MzE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/3.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/3"
  status = 301
  force = true

### 4 ###
[[redirects]]
  from = "/4"
  to = "https://pseudo-flix.pro/media/tmdb-movie-60243-a-separation"
  status = 301
  force = true

[[redirects]]
  from = "/4.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMDM0ZWRmMzctM2M5ZS00ZjU0LWIxN2MtNWNlNGY1ZDhjMDVhXkEyXkFqcGc@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/4.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/4"
  status = 301
  force = true

### 5 ###
[[redirects]]
  from = "/5"
  to = "https://pseudo-flix.pro/media/tmdb-movie-12244-9"
  status = 301
  force = true

[[redirects]]
  from = "/5.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTY2ODE1MTgxMV5BMl5BanBnXkFtZTcwNTM1NTM2Mg@@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/5.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/5"
  status = 301
  force = true

### 6 ###
[[redirects]]
  from = "/6"
  to = "https://youtu.be/zuQYlgL73o0?si=iqPIH1WgbS2cjcoR"
  status = 301
  force = true

[[redirects]]
  from = "/6.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTU5Njc1NjkxMl5BMl5BanBnXkFtZTgwNTkzNTQwMDE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/6.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/6"
  status = 301
  force = true

### 7 ###
[[redirects]]
  from = "/7"
  to = "https://pseudo-flix.pro/media/tmdb-movie-9036-eight-below"
  status = 301
  force = true

[[redirects]]
  from = "/7.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMjExMjAwNzE0N15BMl5BanBnXkFtZTYwMDY4NDk2._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/7.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/7"
  status = 301
  force = true

### 8 ###
[[redirects]]
  from = "/8"
  to = "https://pseudo-flix.pro/media/tmdb-movie-68256-stanley-ka-dabba"
  status = 301
  force = true

[[redirects]]
  from = "/8.poster"
  to = "https://m.media-amazon.com/images/M/MV5BZWVlMzlmOWItYTgwMi00MjExLTgwNDItNWI4YzY2MTgzMWJlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/8.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/8"
  status = 301
  force = true

### 9 ###
[[redirects]]
  from = "/9"
  to = "https://pseudo-flix.pro/media/tmdb-movie-266038-titli"
  status = 301
  force = true

[[redirects]]
  from = "/9.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYTY3MTQzZTMtNzdjOC00NjQ1LTg4ZTgtZTk2NDIzMjE3Yjg0XkEyXkFqcGdeQXVyMzQ5Njc3NzU@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/9.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/9"
  status = 301
  force = true

### 10 ###
[[redirects]]
  from = "/10"
  to = "https://pseudo-flix.pro/media/tmdb-movie-212778-chef"
  status = 301
  force = true

[[redirects]]
  from = "/10.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYTQyNDQwMjYtZTY5YS00MGU2LWE5NzctMjM4Y2IyYjkwMjNkXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/10.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/10"
  status = 301
  force = true

### 11
[[redirects]]
  from = "/11"
  to = "https://www.youtube.com/watch?v=Nxn_6kHVYdc"
  status = 301
  force = true

[[redirects]]
  from = "/11.poster"
  to = "https://m.media-amazon.com/images/M/MV5BY2YzZmEwZjAtYjg4NC00NzA2LWIwYzMtM2M5MGRlNzVmMDMwXkEyXkFqcGdeQXVyOTA4MzYxMzU@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/11.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/11"
  status = 301
  force = true

### 12
[[redirects]]
  from = "/12"
  to = "https://pseudo-flix.pro/media/tmdb-movie-68734-argo"
  status = 301
  force = true

[[redirects]]
  from = "/12.poster"
  to = "https://m.media-amazon.com/images/M/MV5BNzljNjY3MDYtYzc0Ni00YjU0LWIyNDUtNTE0ZDRiMGExMjZlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/12.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/12"
  status = 301
  force = true

### 13
[[redirects]]
  from = "/13"
  to = "https://pseudo-flix.pro/media/tmdb-movie-12289-red-cliff"
  status = 301
  force = true

[[redirects]]
  from = "/13.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTcyOTQ3NDA1OV5BMl5BanBnXkFtZTcwMDY3NzM4Mg@@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/13.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/13"
  status = 301
  force = true

### 14
[[redirects]]
  from = "/14"
  to = "https://pseudo-flix.pro/media/tmdb-movie-18079-nine-queens"
  status = 301
  force = true

[[redirects]]
  from = "/14.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYzE5NTVmYjUtMmE2Ni00OTY5LWJkYTgtZmNmYTM4NDE0YTMzXkEyXkFqcGdeQXVyMTcwOTQzOTYy._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/14.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/14"
  status = 301
  force = true

### 15
[[redirects]]
  from = "/15"
  to = "https://pseudo-flix.pro/media/tmdb-movie-10775-infernal-affairs"
  status = 301
  force = true

[[redirects]]
  from = "/15.poster"
  to = "https://m.media-amazon.com/images/M/MV5BODMzOGVmZDktMGNjNS00NzJkLWJiZGUtNTU1YTIyMzI4Njc4XkEyXkFqcGdeQXVyNDgyODgxNjE@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/15.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/15"
  status = 301
  force = true

### 16
[[redirects]]
  from = "/16"
  to = "https://pseudo-flix.pro/media/tmdb-movie-16553-little-manhattan"
  status = 301
  force = true

[[redirects]]
  from = "/16.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYjM2NzFlYTAtMjI1OS00YThkLWJkNGMtZGFhZDRjY2RiZjExXkEyXkFqcGdeQXVyNjI4MjU4MTY@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/16.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/16"
  status = 301
  force = true

### 17
[[redirects]]
  from = "/17"
  to = "https://pseudo-flix.pro/media/tmdb-movie-1393-the-cave-of-the-yellow-dog"
  status = 301
  force = true

[[redirects]]
  from = "/17.poster"
  to = "https://m.media-amazon.com/images/M/MV5BZjdlZmZiYmMtOGY5ZC00ZDkwLWFkNGYtMWY3OTQyOTYzNmY0XkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/17.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/17"
  status = 301
  force = true

### 18
[[redirects]]
  from = "/18"
  to = "https://pseudo-flix.pro/media/tmdb-movie-1542-office-space"
  status = 301
  force = true

[[redirects]]
  from = "/18.poster"
  to = "https://m.media-amazon.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/18.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/18"
  status = 301
  force = true

### 19
[[redirects]]
  from = "/19"
  to = "https://pseudo-flix.pro/media/tmdb-movie-348678-a-man-called-ove"
  status = 301
  force = true

[[redirects]]
  from = "/19.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMjE0NDUyOTc2MV5BMl5BanBnXkFtZTgwODk2NzU3OTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/19.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/19"
  status = 301
  force = true

### 20
[[redirects]]
  from = "/20"
  to = "https://pseudo-flix.pro/media/tmdb-movie-381284-hidden-figures"
  status = 301
  force = true

[[redirects]]
  from = "/20.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMzgxZTNhYjAtYmM1OC00NjVlLThiYTAtZmFjYjQwOTZiMjcyXkEyXkFqcGdeQXVyMjQ5NjgwMjA@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/20.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/20"
  status = 301
  force = true

### 21
[[redirects]]
  from = "/21"
  to = "https://pseudo-flix.pro/media/tmdb-movie-472454-ayla-the-daughter-of-war"
  status = 301
  force = true

[[redirects]]
  from = "/21.poster"
  to = "https://m.media-amazon.com/images/M/MV5BZjE2NGYwMGQtOWE4MC00NTFjLTk3YTgtMWI5ZmZlMzUyYzExXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/21.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/21"
  status = 301
  force = true

### 22
[[redirects]]
  from = "/22"
  to = "https://pseudo-flix.pro/media/tmdb-movie-209185-the-grand-seduction"
  status = 301
  force = true

[[redirects]]
  from = "/22.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMjI3NTEwMjk0MV5BMl5BanBnXkFtZTgwODUxMTI1MTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/22.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/22"
  status = 301
  force = true

### 23
[[redirects]]
  from = "/23"
  to = "https://pseudo-flix.pro/media/tmdb-movie-109410-42"
  status = 301
  force = true

[[redirects]]
  from = "/23.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTQwMDU4MDI3MV5BMl5BanBnXkFtZTcwMjU1NDgyOQ@@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/23.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/23"
  status = 301
  force = true

### 24
[[redirects]]
  from = "/24"
  to = "https://pseudo-flix.pro/media/tmdb-movie-10315-fantastic-mr-fox"
  status = 301
  force = true

[[redirects]]
  from = "/24.poster"
  to = "https://m.media-amazon.com/images/M/MV5BOGUwYTU4NGEtNDM4MS00NDRjLTkwNmQtOTkwMWMyMjhmMjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/24.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/24"
  status = 301
  force = true

### 25
[[redirects]]
  from = "/25"
  to = "https://pseudo-flix.pro/media/tmdb-movie-21334-children-of-heaven"
  status = 301
  force = true

[[redirects]]
  from = "/25.poster"
  to = "https://m.media-amazon.com/images/M/MV5BZTYwZWQ4ZTQtZWU0MS00N2YwLWEzMDItZWFkZWY0MWVjODVhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/25.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/25"
  status = 301
  force = true

### 26
[[redirects]]
  from = "/26"
  to = "https://pseudo-flix.pro/media/tmdb-movie-49517-tinker-tailor-soldier-spy"
  status = 301
  force = true

[[redirects]]
  from = "/26.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTU2OTkwNzMyM15BMl5BanBnXkFtZTcwOTI4ODg2Ng@@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/26.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://cracko.netlify.app/26"
  status = 301
  force = true
