### 1 ###
[[redirects]]
  from = "/1"
  to = "https://pseudo-flix.pro/media/tmdb-movie-776503-coda"
  status = 301
  force = true

[[redirects]]
  from = "/1.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYzkyNzNiMDItMGU1Yy00NmEyLWE4N2ItMjkzMDZmMmVhNDU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/1.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/1"
  status = 301
  force = true

### 2 ###
[[redirects]]
  from = "/2"
  to = "https://www.youtube.com/watch?v=2ErfXLkVBMY"
  status = 301
  force = true

[[redirects]]
  from = "/2.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTY4YjY3ZDgtYjVhZS00MWY4LTlkYmMtNGI4ZGY4YzhiZmIwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/2.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/2"
  status = 301
  force = true

### 3 ###
[[redirects]]
  from = "/3"
  to = "https://pseudo-flix.pro/media/tmdb-movie-15859-a-moment-to-remember"
  status = 301
  force = true

[[redirects]]
  from = "/3.poster"
  to = "https://m.media-amazon.com/images/M/MV5BODYzODg5Mjg3Ml5BMl5BanBnXkFtZTgwNDM1MDQ2MzE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/3.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/3"
  status = 301
  force = true

### 4 ###
[[redirects]]
  from = "/4"
  to = "https://pseudo-flix.pro/media/tmdb-movie-60243-a-separation"
  status = 301
  force = true

[[redirects]]
  from = "/4.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMDM0ZWRmMzctM2M5ZS00ZjU0LWIxN2MtNWNlNGY1ZDhjMDVhXkEyXkFqcGc@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/4.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/4"
  status = 301
  force = true

### 5 ###
[[redirects]]
  from = "/5"
  to = "https://pseudo-flix.pro/media/tmdb-movie-12244-9"
  status = 301
  force = true

[[redirects]]
  from = "/5.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTY2ODE1MTgxMV5BMl5BanBnXkFtZTcwNTM1NTM2Mg@@._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/5.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/5"
  status = 301
  force = true

### 6 ###
[[redirects]]
  from = "/6"
  to = "https://youtu.be/zuQYlgL73o0?si=iqPIH1WgbS2cjcoR"
  status = 301
  force = true

[[redirects]]
  from = "/6.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMTU5Njc1NjkxMl5BMl5BanBnXkFtZTgwNTkzNTQwMDE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/6.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/6"
  status = 301
  force = true

### 7 ###
[[redirects]]
  from = "/7"
  to = "https://pseudo-flix.pro/media/tmdb-movie-9036-eight-below"
  status = 301
  force = true

[[redirects]]
  from = "/7.poster"
  to = "https://m.media-amazon.com/images/M/MV5BMjExMjAwNzE0N15BMl5BanBnXkFtZTYwMDY4NDk2._V1_FMjpg_UX1000_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/7.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/7"
  status = 301
  force = true

### 8 ###
[[redirects]]
  from = "/8"
  to = "https://pseudo-flix.pro/media/tmdb-movie-68256-stanley-ka-dabba"
  status = 301
  force = true

[[redirects]]
  from = "/8.poster"
  to = "https://m.media-amazon.com/images/M/MV5BZWVlMzlmOWItYTgwMi00MjExLTgwNDItNWI4YzY2MTgzMWJlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/8.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/8"
  status = 301
  force = true

### 9 ###
[[redirects]]
  from = "/9"
  to = "https://pseudo-flix.pro/media/tmdb-movie-266038-titli"
  status = 301
  force = true

[[redirects]]
  from = "/9.poster"
  to = "https://m.media-amazon.com/images/M/MV5BYTY3MTQzZTMtNzdjOC00NjQ1LTg4ZTgtZTk2NDIzMjE3Yjg0XkEyXkFqcGdeQXVyMzQ5Njc3NzU@._V1_.jpg"
  status = 301
  force = true


[[redirects]]
  from = "/9.qr"
  to = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://movieredirect.netlify.app/9"
  status = 301
  force = true
